'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

function detectLineEnding(text) {
  return text.includes('\r\n') ? '\r\n' : '\n';
}

function normalizeParameters(parameters) {
  const source = parameters && typeof parameters === 'object' ? parameters : {};
  const out = {};

  Object.keys(source).forEach((key) => {
    const raw = source[key];
    out[String(key)] = raw === undefined || raw === null ? '' : String(raw);
  });

  return out;
}

function normalizePluginEntry(entry) {
  const source = entry && typeof entry === 'object' ? entry : {};

  return {
    name: source.name === undefined || source.name === null ? '' : String(source.name),
    status: Boolean(source.status),
    description: source.description === undefined || source.description === null ? '' : String(source.description),
    parameters: normalizeParameters(source.parameters)
  };
}

function parsePluginsArrayFromFileText(fileText) {
  const sandbox = {};
  const context = vm.createContext(sandbox);
  const scriptText = `${fileText}\nthis.__plugins__ = (typeof $plugins !== 'undefined') ? $plugins : [];`;

  const script = new vm.Script(scriptText, {
    filename: 'plugins.js'
  });

  script.runInContext(context, { timeout: 1500 });

  if (!Array.isArray(sandbox.__plugins__)) {
    throw new Error('Invalid plugins.js: $plugins is not an array');
  }

  return sandbox.__plugins__.map(normalizePluginEntry);
}

function loadPluginsFile(filePath) {
  const text = fs.readFileSync(filePath, 'utf8');
  const lineEnding = detectLineEnding(text);
  const plugins = parsePluginsArrayFromFileText(text);

  return {
    plugins,
    lineEnding,
    originalText: text
  };
}

function stringifyPluginsFile(plugins, lineEnding) {
  const eol = lineEnding || '\r\n';
  const normalized = Array.isArray(plugins) ? plugins.map(normalizePluginEntry) : [];

  return [
    '// Generated by RPG Maker.',
    '// Do not edit this file directly.',
    'var $plugins =',
    `${JSON.stringify(normalized, null, 2)};`,
    ''
  ].join(eol);
}

function savePluginsFile(filePath, plugins, lineEnding) {
  const text = stringifyPluginsFile(plugins, lineEnding);
  fs.writeFileSync(filePath, text, 'utf8');
}

function resolvePluginsBackupPath(filePath) {
  const sourcePath = String(filePath || '').trim();
  const baseBackupPath = `${sourcePath}-bak`;

  if (!fs.existsSync(baseBackupPath)) {
    return baseBackupPath;
  }

  let index = 1;
  while (fs.existsSync(`${baseBackupPath}${index}`)) {
    index += 1;
  }

  return `${baseBackupPath}${index}`;
}

function backupPluginsFile(filePath) {
  const sourcePath = String(filePath || '').trim();
  if (!sourcePath) {
    throw new Error('Missing plugins.js path');
  }

  if (!fs.existsSync(sourcePath)) {
    throw new Error('plugins.js file not found');
  }

  const backupPath = resolvePluginsBackupPath(sourcePath);
  fs.copyFileSync(sourcePath, backupPath);

  return {
    backupPath,
    backupFileName: path.basename(backupPath)
  };
}

module.exports = {
  detectLineEnding,
  loadPluginsFile,
  normalizePluginEntry,
  backupPluginsFile,
  savePluginsFile,
  stringifyPluginsFile
};
